import dta from "../../../public/userdata.json";
/**
 * This data was generated by using FakerJS.
 */
export async function GET(_: Request) {
  return new Response(JSON.stringify(dta, null, 2), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
  });
}
